=== babudesa/TestProject/modules/scheduler-config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xsd:element name="CronSchedule">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
      <!-- This is the day of month for repeating based on day of month.  Or '*' for every day
           of the month, or '?' if selecting by day of week. -->
      <xsd:attribute name="dayofmonth" type="xsd:string" default="*"/>
      <!-- This is the day 0-7 for repeating based on that day.  Or '?' if ignore day of week
           (using day of month). -->
      <xsd:attribute name="dayofweek" type="xsd:string" default="?"/>
      <!-- This is the hours for repeating based on hours. Or '*' if every hour. -->
      <xsd:attribute name="hours" type="xsd:string" default="*"/>
      <!-- This is the minutes for repeating based on minutes.  Or '*' if every minute.  Defaults
           to '0'. -->
      <xsd:attribute name="minutes" type="xsd:string" default="0"/>
      <!-- This is the month numbers for only those months.  Or '*' for every month. -->
      <xsd:attribute name="month" type="xsd:string" default="*"/>
      <!-- This is the seconds for repeating based on seconds.  Or '*' if every second.  Defaults
           to '0'. -->
      <xsd:attribute name="seconds" type="xsd:string" default="0"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="ProcessSchedule">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="CronSchedule" minOccurs="0" maxOccurs="1"/>
      </xsd:choice>
      <!-- This is the batch process that is being scheduled. -->
      <xsd:attribute name="process" type="ProcessType" use="required"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:simpleType name="ProcessType">
    <xsd:restriction base="xsd:NMTOKEN">
      <!-- Activity escalation monitor -->
      <xsd:enumeration value="ActivityEsc"/>
      <!-- Archiving Item Writer -->
      <xsd:enumeration value="Archive"/>
      <!-- Escalate Bulk Invoices from Awaiting-submission status to Requesting status -->
      <xsd:enumeration value="BulkInvoiceEsc"/>
      <!-- Transitions invoices from PendingInvoiceItemValidation status to 'AwaitingSubmission'
           or 'InvalidInvoiceItems' status once the invoice is ready -->
      <xsd:enumeration value="BulkInvoiceWF"/>
      <!-- Purge records through table updates -->
      <xsd:enumeration value="BulkPurge"/>
      <!-- Finds possible claims related to a catastrophe and creates a 'Review for Catastrophe'
           activity on the claim. -->
      <xsd:enumeration value="CatastropheClaimFinder"/>
      <!-- Claim exception Monitor -->
      <xsd:enumeration value="ClaimException"/>
      <!-- Calculates health indictators and metrics for all claims that do not have any metrics
           calculated -->
      <xsd:enumeration value="ClaimHealthCalc"/>
      <!-- Bulk claim validation work queue writer.  Creates workitems to schedule loaded claims
           for validation -->
      <xsd:enumeration value="ClaimValidation"/>
      <!-- Automatically synchronize the local contact that are out of syn and marked 'allow'
           auto-sync. -->
      <xsd:enumeration value="ContactAutoSync"/>
      <!-- Database statistics -->
      <xsd:enumeration value="DBStats"/>
      <!-- Statistics for the executive dashboard -->
      <xsd:enumeration value="DashboardStatistics"/>
      <!-- Upgrades encryption for entity fields -->
      <xsd:enumeration value="EncryptionUpgrade"/>
      <!-- Creates a new ExchangeRateSet using ExchangeRateSetPlugin -->
      <xsd:enumeration value="ExchangeRate"/>
      <!-- Financials escalation monitor - escalates checks from Awaiting-submission status to
           Requesting status so that the downstream system will be alerted -->
      <xsd:enumeration value="FinancialsEsc"/>
      <!-- Geocoding Addresses queue writer. -->
      <xsd:enumeration value="Geocode"/>
      <!-- Group exception Monitor -->
      <xsd:enumeration value="GroupException"/>
      <!-- Idle claim exception monitor -->
      <xsd:enumeration value="IdleClaim"/>
      <!-- Invoke plugin on completion of monitored worker queue -->
      <xsd:enumeration value="ProcessCompletionMonitor"/>
      <!-- Purge batch process history data -->
      <xsd:enumeration value="ProcessHistoryPurge"/>
      <!-- Purge failed work items from all queues. -->
      <xsd:enumeration value="PurgeFailedWorkItems"/>
      <!-- Purges old messages from the message history table -->
      <xsd:enumeration value="PurgeMessageHistory"/>
      <!-- Purge profiler data at regular intervals -->
      <xsd:enumeration value="PurgeProfilerData"/>
      <!-- Purge completed workflows logs, this executes gw.processes.PurgeWorkflowLogs.gs -->
      <xsd:enumeration value="PurgeWorkflowLogs"/>
      <!-- Purge completed workflows after resetting any referenced workflows, this executes
           gw.processes.PurgeWorkflow.gs -->
      <xsd:enumeration value="PurgeWorkflows"/>
      <!-- Recalculates claim metrics for claims whose metric update time has passed. -->
      <xsd:enumeration value="RecalculateMetrics"/>
      <!-- Transmits completed reviews to ContactCenter. -->
      <xsd:enumeration value="ReviewSync"/>
      <!-- Statistics calculator -->
      <xsd:enumeration value="Statistics"/>
      <!-- TAccounts escalation monitor to transition payments and reserves from FutureDated
           state to Awaiting-submission state -->
      <xsd:enumeration value="TAccountEsc"/>
      <!-- User exception Monitor -->
      <xsd:enumeration value="UserException"/>
      <!-- Purge instrumentation data for work queues -->
      <xsd:enumeration value="WorkQueueInstrumentationPurge"/>
      <!-- Create work items to sechedule marking domain data for archive. -->
      <xsd:enumeration value="Workflow"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:element name="Schedule">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ProcessSchedule" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== babudesa/TestProject/modules/cc/config/scheduler/scheduler-config.xml
<?xml version="1.0"?>
<Schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scheduler-config.xsd">
  <!-- Claim Exception monitoring occurs every day at 2AM -->
  <ProcessSchedule process="ClaimException">
    <CronSchedule hours="2"/>
  </ProcessSchedule>
  <!-- User Exception monitoring occurs every day at 3AM -->
  <ProcessSchedule process="UserException">
    <CronSchedule hours="3"/>
  </ProcessSchedule>
  <!-- Group Exception monitoring occurs every day at 4AM -->
  <ProcessSchedule process="GroupException">
    <CronSchedule hours="4"/>
  </ProcessSchedule>
  <!-- Activity Escalation happens every 30 minutes -->
  <ProcessSchedule process="ActivityEsc">
    <CronSchedule minutes="0,30"/>
  </ProcessSchedule>
  <!-- Financials Escalation occurs every day at 6:05AM and 6:05PM -->
  <ProcessSchedule process="FinancialsEsc">
    <CronSchedule hours="6,18" minutes="5"/>
  </ProcessSchedule>
  <!-- BulkInvoices Escalation occurs every day at 6:35AM and 6:35PM -->
  <ProcessSchedule process="BulkInvoiceEsc">
    <CronSchedule hours="6,18" minutes="35"/>
  </ProcessSchedule>
  <!-- BulkInvoices workflow occurs every 30 minutes -->
  <ProcessSchedule process="BulkInvoiceWF">
    <CronSchedule minutes="0,30"/>
  </ProcessSchedule>
  <!-- TAccounts Escalation occurs every day at 12:01AM. This moves Checks/Payments scheduled for today
       into AwaitingSubmission status. Please refer to the documentation for more information. -->
  <ProcessSchedule process="TAccountEsc">
    <CronSchedule hours="0" minutes="1"/>
  </ProcessSchedule>
  <!-- Idle claim exception monitoring happens at noon on Sunday every week -->
  <ProcessSchedule process="IdleClaim">
    <CronSchedule dayofmonth="?" dayofweek="SUN" hours="12"/>
  </ProcessSchedule>
  <!-- Calculate stats every hour at 3 past the hour -->
  <ProcessSchedule process="Statistics">
    <CronSchedule minutes="3"/>
  </ProcessSchedule>
  <!-- Calculate dashboard stats every night at 1 am -->
  <ProcessSchedule process="DashboardStatistics">
    <CronSchedule hours="1"/>
  </ProcessSchedule>
  <!-- Workflow process executes every ten minutes unless any WorkflowType is mapped
       to the "fastinternal" handler, in which case the workflow process will execute
       once every ten seconds.  Workflow cannot advance any faster in the background
       than this schedule. -->
  <ProcessSchedule process="Workflow">
    <CronSchedule minutes="5,15,25,35,45,55"/>
  </ProcessSchedule>
  <ProcessSchedule process="PurgeProfilerData">
    <CronSchedule hours="2"/>
  </ProcessSchedule>
  <!-- Find metrics that need recalculation every night at 3:30 -->
  <ProcessSchedule process="RecalculateMetrics">
    <CronSchedule hours="3" minutes="30"/>
  </ProcessSchedule>
  <!-- Purge old messages in the claim history table at 4:30 am every Sunday -->
  <ProcessSchedule process="PurgeMessageHistory">
    <CronSchedule dayofmonth="?" dayofweek="SUN" hours="4" minutes="30"/>
  </ProcessSchedule>
  <!-- Run the first of every month after midnight-->
  <ProcessSchedule process="PurgeFailedWorkItems">
    <CronSchedule dayofmonth="1" hours="1"/>
  </ProcessSchedule>
    <!-- Upgrade encryption on snapshots at 1 am every day -->
  <ProcessSchedule process="EncryptionUpgrade">
      <CronSchedule hours="1"/>
  </ProcessSchedule>
  <!-- Find claims that are related to a catastrophe every night at 4:30 -->
  <ProcessSchedule process="CatastropheClaimFinder">
    <CronSchedule hours="4" minutes="30"/>
  </ProcessSchedule>

  <!-- New addresses searched for geocoding at 1:30 am -->
<!--
  <ProcessSchedule process="Geocode">
      <CronSchedule hours="1" minutes="30"/>
  </ProcessSchedule>
-->
  <!-- Create a new ExchangeRateSet every day at 2 am; requires IExchangeRateSetPlugin to be configured and enabled -->
<!--
  <ProcessSchedule process="ExchangeRate">
    <CronSchedule hours="2"/>
  </ProcessSchedule>
-->
  <!-- Contact Auto Sync batch process should run every day at 3 am -->
<!--
  <ProcessSchedule process="ContactAutoSync">
    <CronSchedule hours="3"/>
  </ProcessSchedule>
-->
  <!-- Enable to transmit Reviews to Contact Center; default is hourly -->
<!--
  <ProcessSchedule process="ReviewSync">
    <CronSchedule minutes="20"/>
  </ProcessSchedule>
-->
  <!-- Add claim metrics to loaded or upgraded claims that don't have them. -->
<!--
  <ProcessSchedule process="ClaimHealthCalc">
      <CronSchedule hours="0" minutes="45"/>
  </ProcessSchedule>
-->

</Schedule>
