=== babudesa/TestProject/modules/cc/gsrc/gw/plugin/ccabintegration/impl/object-filter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="ObjectFilter">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="FieldFilter" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="FieldFilter">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Field" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="entity" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Field"/>

</xsd:schema>

=== babudesa/TestProject/modules/configuration/gsrc/gw/plugin/ccabintegration/impl/search-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObjectFilter
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://www.guidewire.com/gwservice/addressbook/object-filter.xsd">

  <FieldFilter entity="ABContact">
    <Field>HomePhone</Field>
    <Field>LinkID</Field>
    <Field>Name</Field>
    <Field>Preferred</Field>
    <Field>PrimaryAddress</Field>
    <Field>PrimaryPhone</Field>
    <Field>Subtype</Field>
    <Field>VendorType</Field>
    <Field>WorkPhone</Field>
    <Field>Score</Field>
    <Field>CellPhoneExt</Field>
    <Field>CMFContactExt</Field>
    <!-- Added Tax-id for Search results Defect # 53 -->
    <Field>TaxID</Field>
    <!-- Added TaxStatus for Search results Defect # 1473 -->
    <Field>Ex_TaxStatusCode</Field>
    <Field>W9Received</Field>
    <Field>W8ReceivedExt</Field>  
  </FieldFilter>

  <FieldFilter entity="ABPerson">
    <Field>CellPhone</Field>
    <Field>FirstName</Field>
    <Field>LastName</Field>
    <Field>Suffix</Field>
  </FieldFilter>

  <FieldFilter entity="Address">
    <Field>AddressLine1</Field>
    <Field>City</Field>
    <Field>PostalCode</Field>
    <Field>State</Field>
    <Field>Country</Field>
    <Field>Latitude</Field>
    <Field>Longitude</Field>
    <Field>HTMID</Field>
    <Field>GeocodeStatus</Field>
  </FieldFilter>-->
</ObjectFilter>
